bet/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace="main")),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from main.site_scheduler import site_updater
site_updater.start()

main/urls.py
from django.urls import path
from . import views


app_name="main"
urlpatterns = [
    path('',views.home, name='home'),
    path('bets/',views.bets, name='mybets'),
    path('transactions/',views.transactions, name='transactions'),
    path('login/', views.loginview, name='login'),
    path('trx/',views.trx,name='trx'),
    path('country/',views.country, name='country'),
    path('referrals/',views.referrals, name='referrals'),
    path('withdraw/<str:user_id>/<str:amount>/',views.withdraw, name='withdraw'),
    ]

main/models.py
import decimal
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid
import requests
from djmoney.models.fields import MoneyField
from djmoney.money import Money
from django_countries.fields import CountryField
import pycountry
from djmoney.contrib.exchange.models import convert_money
from babel.numbers import get_territory_currencies
import os
import sys
from dotenv import load_dotenv,find_dotenv
load_dotenv(find_dotenv(sys.path[0]+'/main/.env'))

API_TOKEN=os.environ.get('API_TOKEN')

ref_value=Money(.2, 'WLD')
def get_currency(code):
    currency = get_territory_currencies(code)[0]
    return currency

def get_referral_id():
    def gen():
        return str(uuid.uuid4())[:6]
    while True:
        ref=gen()
        if not Profile.objects.filter(referral_id=ref).exists():
            return ref
        


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile=Profile.objects.create(user=instance)
        profile.referral_id=get_referral_id()



@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Profile(models.Model):

    SU= User.objects.filter(is_superuser=True).last().pk
    referee=models.ForeignKey(User,on_delete=models.SET_DEFAULT, default=SU, related_name='referral', blank=True, null=True)
    user=models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone=models.CharField(max_length=20)
    country=CountryField(default='KE') #alpha3
    referral_id=models.CharField(max_length=6)
    total_deposit=MoneyField(max_digits=14, decimal_places=2, default_currency='WLD', default=Money(0,'WLD'))
    is_valid = models.BooleanField(default=False)
    balance=MoneyField(max_digits=14, decimal_places=2, default_currency='WLD', default=Money(0,'WLD'))
    bonus=MoneyField(max_digits=14, decimal_places=2, default_currency='WLD', default=Money(0,'WLD'))
    redeem=models.IntegerField(default=0)
    image=models.ImageField(blank=True, upload_to='uploads/dp/',null=True, default='default.png')
    address=models.CharField(max_length=256, blank=True, null=True)
    chat_id=models.CharField(max_length=200)

    def get_balance(self):
        balance= convert_money(self.balance,self.user_currency())
        return balance.amount.quantize(decimal.Decimal('.01'))

    def credit(self,amount):
        cred=Money(amount,'WLD')
        self.balance+=cred
        self.total_deposit+=cred
        self.save()
        minv=Money(.5,'WLD')
        if cred > minv:
            self.is_valid = True

        transaction=Transaction.objects.create(user=self.user,type='cred',amount=cred)
        transaction.save()
        bank=User.objects.get(username='bank')
        bank.profile.balance-=cred
    def debit(self,amount):
        self.balance-=Money(amount,'WLD')
        self.save()
        transaction=Transaction.objects.create(user=self.user,type='debi',amount=Money(amount,'WLD'))
        transaction.save()
        bank=User.objects.get(username='bank')
        bank.profile.balance-=Money(amount,'WLD')


    def deposit(self,amount):
        depo=Money(amount,'WLD')
        self.balance+=depo
        if self.total_deposit==Money(0,'WLD') and depo>Money(2,'WLD'):
            self.bonus=depo*.25
        self.total_deposit+=depo
        self.save()
        transaction=Transaction.objects.create(user=self.user,type='depo',amount=depo)
        transaction.save()
        bank=User.objects.get(username='bank')
        bank.profile.balance+=Money(amount,'WLD')

    def withdraw(self,amount):
        if self.balance>=Money(amount,'WLD'):
            self.balance-=Money(amount,'WLD')
            self.save()
            transaction=Transaction.objects.create(user=self.user,type='with',amount=Money(amount,'WLD'))
            #TODO trx hash
            transaction.save()
            bank=User.objects.get(username='bank')
            bank.profile.balance-=Money(amount,'WLD')
        else:
            raise ValueError('Insufficient balance')

    def user_currency(self):
        currency=get_currency(self.country.code)
        return currency
    
    def unredeemed_refs(self):
        ref=Profile.objects.filter(referee=self.user)
        num=ref.filter(is_valid=True)
        return num.count()*convert_money(ref_value, 'WLD')
    
    def has_withdrawn(self):
        transactions=Transaction.objects.filter(user=self.user)
        withdraws=transactions.filter(type='with')
        if withdraws.count()>0:
            return True
        else:
            return False

    def __str__(self):
        return str(self.user)
      

class Match(models.Model):
    class stageChoices(models.TextChoices):
        SCHEDULED = 'sche','scheduled'
        LIVE = 'li','live'
        FINISHED = 'fin','finished'
        POSTPONED = 'post','postponed'
        PENALTY = 'pen','after penalty'
        PENDING = 'pend','pending results'
        CANCELLED = 'canc','match cancelled'


    class resultChoices(models.TextChoices):
        PENDING = 'pend','pending'
        HOME = 'home','home win'
        DRAW = 'draw','match drawn'
        AWAY = 'away','away win'
        VOID = 'void','match void'

    class Meta:
        verbose_name_plural = 'Matches'
        ordering = ['-created']


    match_id = models.CharField(max_length=100, primary_key=True)
    title = models.CharField(max_length=100)
    home = models.CharField(max_length=100)
    away = models.CharField(max_length=100)
    time = models.DateTimeField()
    stage = models.CharField(max_length=10, choices=stageChoices.choices, default=stageChoices.SCHEDULED)
    #TODO fix other outcomes
    home_odds = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    draw_odds = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    away_odds = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    home_score = models.IntegerField(null=True, blank=True)
    away_score = models.IntegerField(null=True, blank=True)    
    outcome = models.CharField(max_length=4, choices=resultChoices.choices, default=resultChoices.PENDING)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    
    def __str__(self):
        return(f'{self.home} vs {self.away} {self.time.strftime("%H:%M")} ')
    

class BetTicket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stake_amount = models.DecimalField(max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    total_odds = models.DecimalField(max_digits=10, decimal_places=2)
    prize=MoneyField(max_digits=14, decimal_places=2, default_currency='WLD', default=Money(0,'WLD'))
    is_won = models.BooleanField(default=False)
    is_settled = models.BooleanField(default=False)


    class Meta:
        ordering = ['-created_at']

    @property
    def local(self):
        return convert_money(self.prize,self.user.profile.user_currency())


    
    def check_win(self):

        def settle_bet():
            if self.is_settled == False:
                #TODO pay
                selections=self.sselections.all()
                if all(selection.is_correct() for selection in selections):
                    self.user.profile.credit(self.prize.amount)
                    url=f"https://api.telegram.org/bot{API_TOKEN}/sendMessage"
                    res=requests.get(url,params={"chat_id":self.user.profile.chat_id,"text":f"Congratulations, you have won {self.local} for bet {self.id}"})
                    print(f'paid {self.prize} to {self.user} for {self}')
                self.is_settled = True
                
        if self.is_won == False:    
            if self.sselections.filter(selection__in=['home', 'draw', 'away']).exists(): # type: ignore
                selections = self.sselections.all() 
                all_correct = all(selection.is_correct() for selection in selections)
                if all_correct:
                    self.is_won = all_correct
                    settle_bet()
            else:
                self.is_won = False
            self.save()

    def __str__(self):
        return (f"bet {self.id}, potential win {self.prize}")

class BetTicketSelection(models.Model):
    class betChoices(models.TextChoices):
        HOME = 'home','home win'
        DRAW = 'draw','match drawn'
        AWAY = 'away','away win'

    bet_ticket = models.ForeignKey(BetTicket, on_delete=models.CASCADE, related_name='sselections')
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    selection = models.CharField(max_length=4, choices=betChoices.choices, default=None)  # e.g., 'team1', 'team2', 'draw'
    odds = models.DecimalField(max_digits=4, decimal_places=2)

    def is_correct(self):
        return self.selection == self.match.outcome

    def __str__(self):
        return (f"bet on {self.match} for {self.selection}")

class Transaction(models.Model):
    class typeChoices(models.TextChoices):
        DEPOSIT='depo','deposit'
        WITHDRAW='with','withdraw'
        DEBIT='debi','debit'
        CREDIT='cred','credit'
    SU= User.objects.filter(is_superuser=True).last().pk
    user=models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=SU)
    type=models.CharField(max_length=10, choices=typeChoices.choices, default=None)
    amount=MoneyField(max_digits=10, decimal_places=2, default_currency='WLD')
    created=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']


    def __str__(self):
        return (self.type + " " + str(self.amount) +" " + str(self.created.strftime('%Y-%m-%d - %H:%M')))
    

class EtherTransaction(models.Model):
    hash=models.CharField(max_length=256)
    from_addr=models.CharField(max_length=256)
    to=models.CharField(max_length=256)
    value=models.FloatField()

main/forms.py
from django import forms
from .models import BetTicketSelection, BetTicket, Profile


class ticketSelectionForm(forms.ModelForm):
    class Meta:
        model = BetTicketSelection
        fields = ['match','selection','odds',]

class ticketForm(forms.ModelForm):
    class Meta:
        model=BetTicket
        fields=['user','stake_amount','total_odds',]

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

from django_countries.fields import CountryField

from django_countries.widgets import CountrySelectWidget

class CustomForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("country",)
        widgets = {"country": CountrySelectWidget()}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>bet</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://kit.fontawesome.com/d48fb8605a.js" crossorigin="anonymous" defer></script>
    <link rel="stylesheet" href="{% static 'jquery.toast.css' %}">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="{% static 'jquery.toast.js' %}"></script>
    <script src="{% static 'trigram.js' %}"></script>
    <script>
        let script = document.createElement('script');
        script.src = "https://telegram.org/js/telegram-web-app.js"
        document.head.append(script);

        script.onload = function() {
            setThemeClass();
        };
    </script>
    <script>$(document).ready(function () {
            $(window).keydown(function (event) {
                if (event.keyCode == 13) {
                    event.preventDefault();
                    return false;
                }
            });
        });</script>


</head>

<body>
    <div class="searchbar">
        <div class="bar space-btn">
            <p class="logo-container">
                {% if logo %}
                <img class="logo" style="transform: rotate(-0.25turn);" src="{% static 'wld.png' %}" alt="">WorldBet
                {% else %}
                <span class="logo"><a href="/"><i class="fa-solid fa-angle-left" aria-hidden="true"></i></a></span>
                {% endif %}
            </p>
            {%block page%}
            {%endblock%}
            {% if logo %}
            <i class="fa-solid fa-magnifying-glass sx" onclick="showSearch()"></i>
            {% else %}
            <i class="fa-solid fa-magnifying-glass" style="visibility: hidden;"></i>

            {%endif%}
        </div>
        <div class="search-input sx hidden" id="search-input">
            <input type="text" id="search">
            <i class="fa-solid fa-xmark" onclick="hideSearch()"></i>
        </div>
    </div>
    {% if request.user.is_authenticated %}
    {% block content %}

    {% endblock content %}
    {%else%}

    <form action="/login/" id="login" method="post" class="hidden">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="submit" class="hidden">
    </form>
    <div class="" id="tg"></div>

    {% endif %}
    <script type="text/javascript">
        var currency = "{{user.profile.user_currency}}";
        var balance = "{{user.profile.get_balance}}";
        var decoded = decodeURIComponent(window.Telegram.WebApp.initData);
        var arr = decoded.split('&');
        var input = []
        var ids = []
        var all = document.getElementsByClassName('container')
        for (let index = 0; index < all.length; index++) {
            var homet = (all[index].children[1].children[0].children[0].textContent.trim() + '-' + index).toUpperCase();
            var awayt = (all[index].children[1].children[0].children[1].textContent.trim() + '-' + index).toUpperCase();
            ids.push(index + '-' + all[index].id)
            input.push(homet);
            input.push(awayt);
        }
        var trigram = TrigramIndex(input);
        var searchElem = document.getElementById("search");
        searchElem.oninput = function () {
            var all = document.getElementsByClassName('container')
            for (let index = 0; index < all.length; index++) {
                all[index].classList.remove('hidden');
                all[index].classList.add('hidden')

            }

            var phrase = searchElem.value;
            var result = trigram.find(phrase.toUpperCase());
            var hits = []
            var currentMatch = 0;
            var levelsPicked = 0;
            var results = 0;
            for (var i in result) {
                results += 1;
                if (result[i].matches != currentMatch) {
                    if (results > 5 || (results > 3 && result[i].matches <= 3)) break;
                    currentMatch = result[i].matches;
                }
                hits.push(result[i].phrase);
            }
            hitIds = []
            if (hits.length > 0) {
                hits.forEach(hit => {
                    ids.forEach(id => {
                        data = id.split('-')
                        if (data[0] == hit.split('-')[1]) {
                            // hitIds.push(data[1])
                            elm = document.getElementById(data[1])
                            elm.classList.remove('hidden')
                        }
                    });

                });

            } else {
                for (let index = 0; index < all.length; index++) {
                    all[index].classList.remove('hidden');
                }

            }
            // let difference = input.filter(x => !hits.includes(x));
            // difference.forEach(id => {
            //     console.log(id)
            //     element=document.getElementById(id.split(' ')[1])
            //     element.classList.add(hidden)                
            // });
        };
        var data = JSON.parse(arr[1].split('=')[1]);
        // var data = { id: "admin" }
    </script>
    <script src="{% static 'script.js'%}"></script>
    {% if messages %}
    {% for message in messages %}
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="{% static 'jquery.toast.js' %}"></script>
    <script>
        console.log('{{message}}');
        $.toast({
            heading: '{{message.tags}}',
            text: '{{message}}',
            showHideTransition: 'slide',
            position: 'top-right',
            hideAfter: 4000,
            icon: '{{message.tags}}'
        })
    </script>
    {% endfor %}
    {% endif %}

</body>

</html>

main/templates/main/bets.html
{% extends 'main/base.html' %}
{% load djmoney %}
{% load static %}
{%block page%}
<p>My Transactions</p>
{%endblock%}
{% block content %}
<div class="detail-container">
{% for bet in bets %}
<div class="bet">
    <div class="info">#{{bet.id}} <p>Amount: {{bet.stake_amount}}</p>
    </div>
    <div class="info"><span>{{bet.created_at|date:"M d, h:i a"}}</span>
        <p> To win: {{bet.local}}</p>
    </div>
    <div class="info">
        {% if bet.is_won %}
        <span style="color: green;">won</span>
        {% else %}
        {%if bet.is_settled %}
        <span style="color: red;">lost</span>
        {% else %}
        <span style="color: orange;">live</span>
        {% endif %}
        {% endif %}
        <div class="down">
            <i class="fa-solid fa-angle-down" onclick="showMore(this)"></i>
        </div>
    </div>
    <div class="selections hidden">
        <hr>
        {% for selection in bet.sselections.all %}
        <div class="selection">
            <div class="s-teams space-btn">
                <p>
                    {% if selection.is_correct %}
                    <i class="fa-solid fa-circle-check" style="color: green;"></i>
                    {% else %}
                    {% if selection.match.stage != 'fin' %}
                    <i class="fa-solid fa-clock" style="color: orange;"></i>
                    {% else %}
                    <i class="fa-solid fa-circle-xmark" style="color: red;"></i>
                    {% endif %}
                    {% endif %}
                    {{selection.match.home}}
                </p>
                <div class="scores">{{selection.match.home_score|default_if_none:"-"}} :
                    {{selection.match.away_score|default_if_none:"-"}} </div>
                <p>{{selection.match.away}} </p>
            </div>
            <div class="pick space-btn">
                <p class="space-btn lighter">Pick: <span>{{selection.selection}}({{selection.odds}})</span></p>
                <p class="space-btn lighter">Outcome: <span>{{selection.match.outcome}}</span></p>
            </div>
        </div>
        {% if forloop.counter != bet.sselections.all.count %}
        <hr>
        {% endif %}
        {% endfor %}
        <div class="up">
            <i class="fa-solid fa-angle-up" onclick="showLess(this)"></i>
        </div>
    </div>
</div>
    {%endfor%}
</div>
<script>Telegram.WebApp.BackButton.show();
Telegram.WebApp.BackButton.onClick(document.location.href = '/');
</script>
    {% endblock content %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="navbar">
    <div onclick="makeActive('#games')"><i class="fa-solid fa-house"></i></div>
    <div class="betslip-icon" id="betslip-icon" onclick="makeActive('#slip')"><i class="fa-solid fa-file"></i></div>
    <div onclick="makeActive('#account')"><i class="fa-solid fa-user"></i></div>
</div>
<div class="home" id="home" >

    <form method="post" id="betform">
        {%csrf_token%}
        <div class="games nav" id="games">
            {% for match in matches %}

            <div class="container" id="{{match.match_id}}">
                <span class="time">{{match.time|date:"M d, h:i a"}}</span>
                <div class="content">
                    <div class="teams">
                        <p>{{match.home}} </p>
                        <p>{{match.away}}</p>
                    </div>
                    <div class="odds">
                        <div class="odds_select">
                            <label>
                                <input type="checkbox" class="radioCheck" name="{{match.match_id}}" id="{{match.match_id}}-{{match.home}}"
                                    value="home" onclick="updateChecked(this)">
                                <span>{{match.home_odds}}</span>
                            </label>
                        </div>
                        <div class="odds_select">
                            <label>
                                <input type="checkbox" class="radioCheck" name="{{match.match_id}}"
                                    id="{{match.match_id}}-draw" value="draw" onclick="updateChecked(this)">
                                <span>{{match.draw_odds}}</span>
                            </label>
                        </div>
                        <div class="odds_select">
                            <label>
                                <input type="checkbox" class="radioCheck" name="{{match.match_id}}" id="{{match.match_id}}-{{match.away}}"
                                    value="away" onclick="updateChecked(this)">
                                <span>{{match.away_odds}}</span>
                            </label>
                        </div>
                    </div>
                </div>
                <br>
            </div>
            {% endfor %}
        </div>
        <div class="slip nav hidden" id="slip">
            <div class="betslip" id="betslip">
                <p>Please make a selection</p>


            </div>
            <hr>
            <div class="bet-amount">
                <div class="inline"><span>Balance</span>
                    <p class="account-balance">{{user.profile.user_currency}} {{user.profile.get_balance}}</p>
                </div>
                <div class="inline"><span>Total Odds</span>
                    <p class="total-odds"> 0</p>
                </div>
                <div class="inline"><span>Payout</span>
                    <p class="payout"> 0</p>
                </div>
                <div class="wrapper">
                    <input class="amount" type="number" name="amount" id="amount" value="100"
                        oninput="updateBetslip(this)">
                    <div class="placeholder">Amount</div>
                </div>
                <button id="submitBtn" disabled type="submit" onclick="load(this)">place bet</button>
            </div>
        </div>

    </form>
</div>
<div class="account nav hidden" id="account">
    <div class="username center">
        <div class="profile-pic">
            <img src="{{user.profile.image.url}}" alt="">
        </div>@IamChrisis
    </div>
    <div class="balances space-btn">
        <div class="main-balance center"><i class="fa-solid fa-wallet"></i>
            <div class="column"><span>Balance</span>
                <p>WLD {{user.profile.balance.amount | floatformat:2}}</p> <span
                    class="small">{{user.profile.user_currency}} {{user.profile.get_balance}}</span>
            </div>
        </div>
        <a href="/referrals">
            <div class="referral-balance center"><i class="fa-solid fa-people-group"></i>
                <div class="column"><span>Referral balance</span>{{user.profile.unredeemed_refs}}</div>
            </div>
        </a>
    </div>
    <div class="transact">
        <div class="deposit transact-content">
            <p>Deposit</p>
            <span>Deposit funds to your account</span>
            <form id="deposit-form" action="{% url 'main:trx' %}" method="get">
                <div class="request">
                    <div class="wrapper addr hidden" id="addr">
                        <span class="address" id="dep-address">0xbc0367e2fd8885ccfbb1032f3ceb7905378e8e5e</span>
                        <div class="copy" onclick="copyContent()">
                            <i class="fa-solid fa-copy"></i> COPY
                        </div>
                    </div>
                    <div class="hidden" id="trx">
                        <div class="wrapper">
                            <input type="text" name="trxcode" id="trxcode" onfocus="hideSpan(this)"
                                onfocusout="showSpan(this)" onchange="disableDeposit(this)">
                            <span class="hash">enter transaction hash</span>
                            <div class="copy" onclick="pasteContent(this); disableDeposit(this);">
                                <i class="fa-solid fa-clipboard"></i> PASTE
                            </div>
                        </div>
                        <div>
                            <p class="small tut" onclick="toggleInstructions()"><i
                                    class="fa-regular fa-circle-question"></i>How to find hash</p>
                            <div class="instructions hidden" id="instructions">
                                <ul>
                                    <li>Open the WorldApp</li>
                                    <li>Go to Wallet</li>
                                    <li>Click on history icon</li>
                                    <li>Find the transaction</li>
                                    <li>Click on details</li>
                                </ul>
                            </div>
                            <button disabled type="button" onclick="checkTrx(this)">Confirm Deposit</button>
                        </div>
                    </div>
                    <button type="button" onclick="showAddr(this)" id="showAddrBtn">request deposit address</button>
                </div>

            </form>

        </div>
        <div class="withdraw transact-content">
            <p>withdraw</p>
            <span>withdraw funds from account</span>
            <form action="{% url 'main:trx' %}" method="post">
                {%csrf_token%}
                <div class="wrapper">
                    <input type="text" name="user-address" id="user-address" onfocus="hideSpan(this)"
                        onfocusout="showSpan(this)">
                    <span class="enter-address">enter worldcoin address</span>
                    <div class="copy" onclick="pasteContent(this)">
                        <i class="fa-solid fa-clipboard"></i> PASTE
                    </div>
                </div>
                <div class="wrapper">
                    <input type="number" step=".01" name="withdraw-amount" id="withdraw-amount"
                        oninput="toggleDisable(this)">
                    <div class="placeholder">Amount(WLD)</div>
                </div>
                <button disabled type="submit" onclick="load(this)">withdraw</button>
            </form>
        </div>
        <div class="mybets btn">
            <a href="{% url 'main:mybets' %}">
                <div><i class="fa-solid fa-clock"></i> bet history</div><i class="fa-solid fa-angle-right"></i>
            </a>
        </div>
        <div class="transactions btn">
            <a href="{% url 'main:transactions' %}">
                <div><i class="fa-solid fa-arrow-down-up-across-line"></i> transaction history</div>
                <i class="fa-solid fa-angle-right"></i>
            </a>
        </div>
        <div class="settings btn space-btn">
            {% load countries %}
            {% get_countries as countries %}
            <form method="post" action="/country/" style="width: 100%;">
                {%csrf_token%}
                <i class="fa-solid fa-angle-down"></i>
                {{country_form.as_p}}
                <button type="submit" onclick="load(this)">Update</button>
            </form>
        </div>
    </div>
</div>
<div class="betslip-container hidden" id="betslip-container">
    <div class="slip-teams">
        <i class="fa fa-remove" onclick="removeMatch(this)"></i>
        <div class="team-details">
            <p></p>
            <span class="pick"></span>
            <span class="time2"></span>
        </div>
    </div>
    <div class="slip-odds">

    </div>
</div>
<script>Telegram.WebApp.BackButton.hide()
</script>
{% endblock content %}

main/templates/main/transactions.html
{%extends 'main/base.html'%}
{%block page%}
<p>My Transactions</p>
{%endblock%}
{% block content %}
<div class="detail-container">
{% for transaction in transactions%}
{% if transaction.type == 'with' or transaction.type == 'depo' %}
<div class="transaction">
    <div class="info">#{{transaction.id}} <p>{{transaction.get_type_display}}</p></div>
    <div class="info"><span>{{transaction.created|date:"M d, h:i a"}}</span> <p> Amount: <span style="font-size: .8rem;font-weight: normal;">WLD</span> {{transaction.amount.amount}}</p></div>

</div>
{%endif%}
{%endfor%}
</div>
<script>Telegram.WebApp.BackButton.show();
Telegram.WebApp.BackButton.onClick(document.location.href = '/');

</script>
{% endblock content %}